### ISSUE TITLE
License

### ISSUE THREAD

**Issue by lupoDharkael** [asmaloney/asmOpenCV#2]
as you said [here](https://asmaloney.com/2013/11/code/converting-between-cvmat-and-qimage-or-qpixmap/#comment-2702)

> Thanks Matthias! (I don’t use this code anymore, so I never ran into this issue…)
> I fixed the code here and on github.
> There is no license – you can do whatever you want with it.

But no license == illegal to use

Read: https://www.gnu.org/licenses/license-list.en.html#NoLicense

**Comment by asmaloney** [comment]
I don't believe that everything has to be owned (or can be owned) or that every scrap of code needs a license. If you believe it's illegal - and are concerned about that - then don't use it.

You have the freedom to choose to use it or not.

**Comment by lupoDharkael** [comment]
In fact that code is owned by the copyright owner (you) by default, and only you have the legal right to modify, redistribute and execute the code.
In this case there is a exception because this code is in Github too so you directly accepted Github's clauses and users are allowed to fork inside their service.
It's as simple to prevent as adding an explicit declaration of license in the Readme and user will be allowed to use your code without legal incompatibilities with their projects.
If you don't want to be the owner of the copyright you can use a public domain license such as [C0](https://creativecommons.org/choose/zero/) or [Do What the Fuck You Want To Public License](http://www.wtfpl.net/)

That would mean people could use your code in their projects without problems, I won't insist, just wanted to give advice.

**Comment by asmaloney** [comment]
Thanks - I understand what you're saying and I understand licensing, and I've chosen to do it this way. 

I fundamentally disagree with the position that everything has to be owned (or can be owned) by someone or that every scrap of code needs a license. Licensing and legal issues are out of control.

> That would mean people could use your code in their projects without problems

People _can_ use it without problems - unless they've chosen to create problems themselves.
